# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ar_condicionado.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61r_condicionado.proto\"\x1c\n\x0cinfo_request\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\x0b\x63hange_temp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08new_temp\x18\x02 \x01(\x05\"7\n\x14\x61r_condicionado_info\x12\n\n\x02on\x18\x01 \x01(\x08\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x32\x8f\x02\n\x0f\x61r_condicionado\x12<\n\x12\x61r_condicionado_on\x12\r.info_request\x1a\x15.ar_condicionado_info\"\x00\x12=\n\x13\x61r_condicionado_off\x12\r.info_request\x1a\x15.ar_condicionado_info\"\x00\x12@\n\x16\x61r_condicionado_status\x12\r.info_request\x1a\x15.ar_condicionado_info\"\x00\x12=\n\x14\x61r_condicionado_temp\x12\x0c.change_temp\x1a\x15.ar_condicionado_info\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ar_condicionado_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFO_REQUEST']._serialized_start=25
  _globals['_INFO_REQUEST']._serialized_end=53
  _globals['_CHANGE_TEMP']._serialized_start=55
  _globals['_CHANGE_TEMP']._serialized_end=100
  _globals['_AR_CONDICIONADO_INFO']._serialized_start=102
  _globals['_AR_CONDICIONADO_INFO']._serialized_end=157
  _globals['_AR_CONDICIONADO']._serialized_start=160
  _globals['_AR_CONDICIONADO']._serialized_end=431
# @@protoc_insertion_point(module_scope)
